name: Run unit tests of llvm-jit

on:
  push:
    branches: "main"
  pull_request: 
    branches: "main"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        container:
          - ubuntu-2204
          - fedora-39
    runs-on: ubuntu-22.04
    container: 
      image: "manjusakalza/bpftime-base-image:${{matrix.container}}"
      options: --privileged
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: build
      run: 
           |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DBPFTIME_ENABLE_UNIT_TESTING=1
          cmake --build build --target all -j

    - name: Run example
      run: |
        ./build/vm-llvm-example

    - name: Run tests
      run: |
        ./build/unit-test/llvm_jit_tests

    - name: build llvm JIT/AOT release as a standalone library
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release &&\
        cmake --build build --target all -j
   
